Series    1D
DataFrame 2D
Panel     3D

In [1]:
import numpy as np
import pandas as pd

In [2]:
x = np.random.randint(9, size= (3, 3))
print(x)
x[x%2==0]

[[4 2 5]
 [4 0 0]
 [5 4 3]]


array([4, 2, 4, 0, 0, 4])

In [3]:
a = np.array([1, 2, 3, 4, 5])
boolarray = [True, False, True, False, True]
a[boolarray]

array([1, 3, 5])

In [4]:
df = pd.DataFrame([{'name': 'bob', 'age':23}, {'name': 'ram', 'age':45}])
df


name  age
0  bob   23
1  ram   45

In [7]:
houseXLS = pd.read_excel('/Volumes/Developer/Tech_Saksham/Unit4(DatAnalysis)/Data/House_Data_xls.xlsx')
houseXLS.head()

area_type         availability                  location  \
0  Super built-up  Area  2020-12-19 00:00:00  Electronic City Phase II   
1            Plot  Area        Ready To Move          Chikka Tirupathi   
2        Built-up  Area        Ready To Move               Uttarahalli   
3  Super built-up  Area        Ready To Move        Lingadheeranahalli   
4  Super built-up  Area        Ready To Move                  Kothanur   

        size  society total_sqft  bath  balcony   price  
0      2 BHK  Coomee        1056   2.0      1.0   39.07  
1  4 Bedroom  Theanmp       2600   5.0      3.0  120.00  
2      3 BHK      NaN       1440   2.0      3.0   62.00  
3      3 BHK  Soiewre       1521   3.0      1.0   95.00  
4      2 BHK      NaN       1200   2.0      1.0   51.00

In [8]:
houseCSV = pd.read_csv('/Volumes/Developer/Tech_Saksham/Unit4(DataAnalysis)/Data/House_Data.csv')
houseCSV.head()

area_type   availability                  location       size  \
0  Super built-up  Area         19-Dec  Electronic City Phase II      2 BHK   
1            Plot  Area  Ready To Move          Chikka Tirupathi  4 Bedroom   
2        Built-up  Area  Ready To Move               Uttarahalli      3 BHK   
3  Super built-up  Area  Ready To Move        Lingadheeranahalli      3 BHK   
4  Super built-up  Area  Ready To Move                  Kothanur      2 BHK   

   society total_sqft  bath  balcony   price  
0  Coomee        1056   2.0      1.0   39.07  
1  Theanmp       2600   5.0      3.0  120.00  
2      NaN       1440   2.0      3.0   62.00  
3  Soiewre       1521   3.0      1.0   95.00  
4      NaN       1200   2.0      1.0   51.00

In [ ]:
dummy = pd.DataFrame()