In [2]:
import numpy as np

In [4]:
arr=np.array([1,2,3])
print(arr)

[1 2 3]


In [6]:
arrOfZeros = np.zeros((2,2)) #create array of 2 by 2 with all elements =0
print(arrOfZeros)

[[0. 0.]
 [0. 0.]]


In [8]:
arrOfOnes=np.ones((3,3)) #create array of 3 by 3 with every element =1
print(arrOfOnes)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [12]:
arrOfRandomVal = np.random.rand(3,3)   # 3x3 matrix with random float values
print(arrOfRandomVal)

[[0.33978016 0.58364562 0.47058121]
 [0.61092364 0.90460401 0.93822424]
 [0.34486112 0.43733049 0.60111054]]


In [14]:
IntArray = np.random.randint(1,10,(3,2)) # 3 by 2 matrix with random integers between 1 to 10
print(IntArray)

[[3 9]
 [2 4]
 [1 7]]
