In [6]:
import numpy as np
arr1=np.array([[1,2,3],[3,4,5],[5,6,7]])
print(arr1)

[[1 2 3]
 [3 4 5]
 [5 6 7]]


In [8]:
arr1[0]

array([1, 2, 3])

In [10]:
arr1[0][0]


1

In [18]:
arr1[0:3,1:3]# row slicing , column slicing

array([[2, 3],
       [4, 5],
       [6, 7]])

In [21]:
arr3=np.random.randint(100,size=(10,10))
print(arr3)

[[ 7  3 13  5  7 35 90 35 14 41]
 [81 95 97 29 49 34 66 17 42 68]
 [78 83  5 67 83 98 65 31  0 41]
 [79 24 99 81 50 29 55 85 63 79]
 [26 77 58 91 14 21 75 57 95 30]
 [42 75 43 86 21 96 84 14 97 69]
 [ 7 18 32 39 60  9 70 95 97 45]
 [21  8 78 41 47 47 23 50 14 82]
 [91 88  5 16 39 40 75 51  7 40]
 [78  8 94 52 45 60 73 58 77 80]]


In [23]:
arr3[:,[1,4,7]]

array([[ 3,  7, 35],
       [95, 49, 17],
       [83, 83, 31],
       [24, 50, 85],
       [77, 14, 57],
       [75, 21, 14],
       [18, 60, 95],
       [ 8, 47, 50],
       [88, 39, 51],
       [ 8, 45, 58]])

In [33]:
arr4=np.random.randint(10,50,(3,3))

In [35]:
arr4=np.random.randint(10,50,(3,3))

In [37]:
print(arr3)

[[ 7  3 13  5  7 35 90 35 14 41]
 [81 95 97 29 49 34 66 17 42 68]
 [78 83  5 67 83 98 65 31  0 41]
 [79 24 99 81 50 29 55 85 63 79]
 [26 77 58 91 14 21 75 57 95 30]
 [42 75 43 86 21 96 84 14 97 69]
 [ 7 18 32 39 60  9 70 95 97 45]
 [21  8 78 41 47 47 23 50 14 82]
 [91 88  5 16 39 40 75 51  7 40]
 [78  8 94 52 45 60 73 58 77 80]]


In [39]:
arr3[arr3%2==0]

array([90, 14, 34, 66, 42, 68, 78, 98,  0, 24, 50, 26, 58, 14, 30, 42, 86,
       96, 84, 14, 18, 32, 60, 70,  8, 78, 50, 14, 82, 88, 16, 40, 40, 78,
        8, 94, 52, 60, 58, 80])

In [47]:
boolArr=np.array([True,True,False,False,True,False])
array=np.array([1,2,3,4,5,6])
array=array[boolArr]
print(array)

[1 2 5]
